name: "ci"

on: [push, pull_request]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: pnpm-store-dir
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps
        run: pnpm i

      - name: build
        run: pnpm build

      # Runs a set of commands using the runners shell
      - name: test
        run: pnpm test

      - name: lint
        run: pnpm lint

  automerge:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          target: "minor"
